-- MySQL Script generated by MySQL Workbench
-- Thu Sep 16 02:28:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema task
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema task
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `task` DEFAULT CHARACTER SET utf8mb4 ;
USE `task` ;

-- -----------------------------------------------------
-- Table `task`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task`.`categories` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `parent_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `categories_parent_id_foreign` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `categories_parent_id_foreign`
    FOREIGN KEY (`parent_id`)
    REFERENCES `task`.`categories` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `task`.`photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task`.`photos` (
  `quiz_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `src` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`quiz_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `task`.`quizzes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task`.`quizzes` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `duration` INT(11) NOT NULL,
  `level` ENUM('hard', 'medium', 'easy') NOT NULL,
  `price` DOUBLE(5,2) NOT NULL,
  `photo_id` BIGINT(20) UNSIGNED NOT NULL,
  `category_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `quizzes_photo_id_foreign` (`photo_id` ASC) VISIBLE,
  INDEX `quizzes_category_id_foreign` (`category_id` ASC) VISIBLE,
  CONSTRAINT `quizzes_category_id_foreign`
    FOREIGN KEY (`category_id`)
    REFERENCES `task`.`categories` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `quizzes_photo_id_foreign`
    FOREIGN KEY (`photo_id`)
    REFERENCES `task`.`photos` (`quiz_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `task`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task`.`questions` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NOT NULL,
  `quiz_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `questions_quiz_id_foreign` (`quiz_id` ASC) VISIBLE,
  CONSTRAINT `questions_quiz_id_foreign`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `task`.`quizzes` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `task`.`choices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task`.`choices` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `choice` VARCHAR(255) NOT NULL,
  `isRight` TINYINT(1) NOT NULL,
  `question_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `choices_question_id_foreign` (`question_id` ASC) VISIBLE,
  CONSTRAINT `choices_question_id_foreign`
    FOREIGN KEY (`question_id`)
    REFERENCES `task`.`questions` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `task`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL DEFAULT 0,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `task`.`choice_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task`.`choice_user` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `choice_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `choice_user_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `choice_user_choice_id_foreign` (`choice_id` ASC) VISIBLE,
  CONSTRAINT `choice_user_choice_id_foreign`
    FOREIGN KEY (`choice_id`)
    REFERENCES `task`.`choices` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `choice_user_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `task`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `task`.`exams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task`.`exams` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `quiz_id` BIGINT(20) UNSIGNED NOT NULL,
  `attempts_available` SMALLINT(6) NOT NULL DEFAULT 1,
  `mark` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `exams_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `exams_quiz_id_foreign` (`quiz_id` ASC) VISIBLE,
  CONSTRAINT `exams_quiz_id_foreign`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `task`.`quizzes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `exams_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `task`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `task`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `task`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `task`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `task`.`personal_access_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task`.`personal_access_tokens` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tokenable_type` VARCHAR(255) NOT NULL,
  `tokenable_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `token` VARCHAR(64) NOT NULL,
  `abilities` TEXT NULL DEFAULT NULL,
  `last_used_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `personal_access_tokens_token_unique` (`token` ASC) VISIBLE,
  INDEX `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type` ASC, `tokenable_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `task`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task`.`skills` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `skill` VARCHAR(255) NOT NULL,
  `category_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `skills_category_id_foreign` (`category_id` ASC) VISIBLE,
  CONSTRAINT `skills_category_id_foreign`
    FOREIGN KEY (`category_id`)
    REFERENCES `task`.`categories` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `task`.`skill_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task`.`skill_user` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `skill_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `skill_user_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `skill_user_skill_id_foreign` (`skill_id` ASC) VISIBLE,
  CONSTRAINT `skill_user_skill_id_foreign`
    FOREIGN KEY (`skill_id`)
    REFERENCES `task`.`skills` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `skill_user_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `task`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
